### ISSUE TITLE
Widget Renderer crashing in Visual Studio Code Python notebooks on Windows

### ISSUE THREAD

**Issue by ayemjay** [hex-inc/vegafusion#260]
Firstly, thanks for the library. 

Experiencing problems using widget renderer with vscode python notebooks on windows:

```vegafusion: v1.0.4
altair: v4.2.2 and v5.0.0rc1
vscode: v1.76.2
jupyter extension: v2023.2.1200692131
jupyter notebook renderers extension: v1.0.15
```

Following code runs fine on above setup on windows:

```python
import altair as alt
import vegafusion as vf
import polars as pl

vf.enable()

alt.Chart(
    pl.DataFrame({"x": [0, 1, 2, 3], "y": [0, 1, 2, 3]}).to_pandas()
).mark_point().encode(x="x", y="y")
```

Changing to enable widget renderer causes vscode/jupyter/python process to crash. This happens on Windows and tested on multiple machines. The code runs fine on macOS however:

```python
import altair as alt
import vegafusion as vf
import polars as pl

vf.enable_widget()

alt.Chart(
    pl.DataFrame({"x": [0, 1, 2, 3], "y": [0, 1, 2, 3]}).to_pandas()
).mark_point().encode(x="x", y="y")
```

Attaching window output, please let me know if any other logs are required:

```
2023-03-18 10:17:50.020 [error] Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
2023-03-18 10:17:50.021 [info] Automatically restarting the extension host.
2023-03-18 10:17:50.029 [error] [stored file working copy] handleSaveError(14) - exit - resulted in a save error: Canceled: Canceled file:///c%3A/Users/Adrian/Development/sandbox/test.ipynb notebook/jupyter-notebook
2023-03-18 10:17:50.560 [error] unknown text editor: 0f979a40-ecee-4375-a0e2-a2cbc65020c7. known editors:  : Error: unknown text editor: 0f979a40-ecee-4375-a0e2-a2cbc65020c7. known editors:  
	at l.getEditorById (../../../vs/workbench/api/worker/extensionHostWorker.js:80:79049)
	at N.$postRendererMessage (../../../vs/workbench/api/worker/extensionHostWorker.js:80:95875)
	at u.N (../../../vs/workbench/api/worker/extensionHostWorker.js:80:186590)
	at u.M (../../../vs/workbench/api/worker/extensionHostWorker.js:80:186308)
	at u.H (../../../vs/workbench/api/worker/extensionHostWorker.js:80:185395)
	at u.G (../../../vs/workbench/api/worker/extensionHostWorker.js:80:184376)
	at eval (../../../vs/workbench/api/worker/extensionHostWorker.js:80:183164)
	at E.invoke (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/base/worker/workerMain.js:16:145)
	at w.deliver (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/base/worker/workerMain.js:16:2070)
	at F.fire (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/base/worker/workerMain.js:16:1708)
	at d.port1.onmessage (../../../vs/workbench/api/worker/extensionHostWorker.js:87:3965)
2023-03-18 10:17:50.567 [error] model index out of range 1: Error: model index out of range 1
    at Ra.kb (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1082:16251)
    at Ra.M (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1082:8504)
    at Ra.applyEdits (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1082:6903)
    at ke.Sc (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2197:34122)
    at vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1863:6546
    at g.invoke (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2066)
    at h.fire (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1704)
    at vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1208:8021
    at vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1208:7683
    at Set.forEach (<anonymous>)
    at w.onmessage (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1208:7671)
2023-03-18 10:17:50.568 [error] model index out of range 0: Error: model index out of range 0
    at Ra.kb (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1082:16251)
    at Ra.M (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1082:8504)
    at Ra.applyEdits (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1082:6903)
    at ke.Sc (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2197:34122)
    at vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1863:6546
    at g.invoke (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2066)
    at h.fire (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1704)
    at vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1208:8021
    at vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1208:7683
    at Set.forEach (<anonymous>)
    at w.onmessage (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1208:7671)
2023-03-18 10:17:50.572 [error] unknown text editor: 0f979a40-ecee-4375-a0e2-a2cbc65020c7. known editors:  : Error: unknown text editor: 0f979a40-ecee-4375-a0e2-a2cbc65020c7. known editors:  
	at l.getEditorById (../../../vs/workbench/api/worker/extensionHostWorker.js:80:79049)
	at N.$acceptEditorPropertiesChanged (../../../vs/workbench/api/worker/extensionHostWorker.js:78:42128)
	at u.N (../../../vs/workbench/api/worker/extensionHostWorker.js:80:186590)
	at u.M (../../../vs/workbench/api/worker/extensionHostWorker.js:80:186308)
	at u.H (../../../vs/workbench/api/worker/extensionHostWorker.js:80:185395)
	at u.G (../../../vs/workbench/api/worker/extensionHostWorker.js:80:184376)
	at eval (../../../vs/workbench/api/worker/extensionHostWorker.js:80:183164)
	at E.invoke (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/base/worker/workerMain.js:16:145)
	at w.deliver (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/base/worker/workerMain.js:16:2070)
	at F.fire (vscode-file://vscode-app/c:/Users/Adrian/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/base/worker/workerMain.js:16:1708)
	at d.port1.onmessage (../../../vs/workbench/api/worker/extensionHostWorker.js:87:3965)
2023-03-18 10:17:50.774 [error] unknown text editor: 0f979a40-ecee-4375-a0e2-a2cbc65020c7. known editors:  : Error: unknown text editor: 0f979a40-ecee-4375-a0e2-a2cbc65020c7. known editors:  
	at u.getEditorById (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:79427)
	at R.$postRendererMessage (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:96239)
	at a.N (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:11223)
	at a.M (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:10941)
	at a.H (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:10034)
	at a.G (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:9015)
	at c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:7803
	at f.invoke (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at m.deliver (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2066)
	at d.fire (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1704)
	at p.fire (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:14907)
	at c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:16556
	at f.invoke (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at m.deliver (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2066)
	at d.fire (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1704)
	at p.fire (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:14907)
	at MessagePortMain.<anonymous> (c:\Users\Adrian\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:122:14682)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
```

**Comment by jonmmease** [comment]
Thanks for the detailed report @ayemjay.  I'm not sure off hand what might be going on here.

@DonJayamanne, if you have a moment, does the above Code stack trace ring any bells for you? Thanks!

**Comment by jonmmease** [comment]
In the mean time, you should be able to use the [Mime Renderer](https://vegafusion.io/mime_renderer.html), which provides most of the benefits of the widget renderer while reusing the standard Altair rendering path.
