### ISSUE TITLE
Error if a color scale has only one value

### ISSUE THREAD

**Issue by binste** [hex-inc/vegafusion#379]
If the `range` and `domain` attributes of a chart have only one value, the `alt.Chart.transformed_data` method returns an error which originates from VegaFusion. If I add a second value, it works. Seems like the parsing logic changes if it's one value?

```python
import altair as alt
import pandas as pd

df = pd.DataFrame([[1, "A"]], columns=["x", "y"])

chart = (
    alt.Chart(df)
    .mark_bar()
    .encode(
        x="x",
        y="y",
        color=alt.Color("y", scale=alt.Scale(range=["#0000FF"], domain=["A"])),
    )
)
chart.transformed_data()
```
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError("Invalid character: #", ErrorContext { contexts: ["Failed to parse token at position 0 in expression: #0000FF"] })', vegafusion-core/src/planning/stitch.rs:27:10
```
Replacing `"#0000FF"` above with `"blue"` gives:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InternalError("Failed to resolve variable Variable { name: \"blue\", namespace: Signal } used in scope []", ErrorContext { contexts: [] })', vegafusion-core/src/planning/stitch.rs:27:10
```

The following works:

```python
chart = (
    alt.Chart(df)
    .mark_bar()
    .encode(
        x="x",
        y="y",
        color=alt.Color("y", scale=alt.Scale(range=["#0000FF", "white"], domain=["A", "B"])),
    )
)
chart.transformed_data()
```
 I noticed this in an application where we generate the `alt.Scale` definition based on the distinct values in a column.

This is on Altair: 5.1.0 and VegaFusion: 1.4.0.

**Comment by jonmmease** [comment]
Thanks for the report. Yeah, something weird is going on here, I'll need to look at the Vega expressions that Vega-Lite is producing.
